# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from PySide2extn.RoundProgressBar import roundProgressBar


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(687, 549)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(238, 238, 236, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        MainWindow.setPalette(palette)
        font = QFont()
        font.setFamily(u"Bitstream Vera Sans Mono")
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u"src/modbus/modbus/picture/teco_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 681, 501))
        font1 = QFont()
        font1.setFamily(u"Bitstream Vera Sans Mono")
        font1.setBold(True)
        font1.setWeight(75)
        self.tabWidget.setFont(font1)
        self.tabWidget.setTabShape(QTabWidget.Triangular)
        self.tab_arm = QWidget()
        self.tab_arm.setObjectName(u"tab_arm")
        self.gridLayoutWidget = QWidget(self.tab_arm)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 30, 271, 348))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.lineEdit_payload_2 = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_payload_2.setObjectName(u"lineEdit_payload_2")

        self.gridLayout.addWidget(self.lineEdit_payload_2, 2, 1, 1, 1)

        self.label_9 = QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(u"label_9")

        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)

        self.label_11 = QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName(u"label_11")

        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)

        self.label_8 = QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(u"label_8")

        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)

        self.label_14 = QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName(u"label_14")

        self.gridLayout.addWidget(self.label_14, 1, 2, 1, 1)

        self.label_13 = QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName(u"label_13")

        self.gridLayout.addWidget(self.label_13, 0, 2, 1, 1)

        self.label_12 = QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName(u"label_12")

        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)

        self.label_19 = QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName(u"label_19")

        self.gridLayout.addWidget(self.label_19, 2, 2, 1, 1)

        self.comboBox_dof = QComboBox(self.gridLayoutWidget)
        self.comboBox_dof.setObjectName(u"comboBox_dof")

        self.gridLayout.addWidget(self.comboBox_dof, 4, 1, 1, 1)

        self.label_18 = QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName(u"label_18")

        self.gridLayout.addWidget(self.label_18, 3, 0, 1, 1)

        self.lineEdit_reachable_radius = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_reachable_radius.setObjectName(u"lineEdit_reachable_radius")

        self.gridLayout.addWidget(self.lineEdit_reachable_radius, 3, 1, 1, 1)

        self.label_22 = QLabel(self.gridLayoutWidget)
        self.label_22.setObjectName(u"label_22")

        self.gridLayout.addWidget(self.label_22, 3, 2, 1, 1)

        self.lineEdit_3_length = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3_length.setObjectName(u"lineEdit_3_length")

        self.gridLayout.addWidget(self.lineEdit_3_length, 1, 1, 1, 1)

        self.lineEdit_2_length = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2_length.setObjectName(u"lineEdit_2_length")

        self.gridLayout.addWidget(self.lineEdit_2_length, 0, 1, 1, 1)

        self.btn_dynamics_design = QPushButton(self.tab_arm)
        self.btn_dynamics_design.setObjectName(u"btn_dynamics_design")
        self.btn_dynamics_design.setGeometry(QRect(530, 200, 141, 33))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush2 = QBrush(QColor(218, 119, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_dynamics_design.setPalette(palette1)
        font2 = QFont()
        font2.setFamily(u"Bitstream Vera Sans")
        font2.setPointSize(11)
        font2.setBold(True)
        font2.setWeight(75)
        self.btn_dynamics_design.setFont(font2)
        self.btn_dynamics_design.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.gridLayoutWidget_2 = QWidget(self.tab_arm)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(290, 20, 221, 444))
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_46 = QLabel(self.gridLayoutWidget_2)
        self.label_46.setObjectName(u"label_46")

        self.gridLayout_2.addWidget(self.label_46, 11, 2, 1, 1)

        self.label_31 = QLabel(self.gridLayoutWidget_2)
        self.label_31.setObjectName(u"label_31")

        self.gridLayout_2.addWidget(self.label_31, 0, 0, 1, 1)

        self.lineEdit_joint5_ = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint5_.setObjectName(u"lineEdit_joint5_")

        self.gridLayout_2.addWidget(self.lineEdit_joint5_, 9, 1, 1, 1)

        self.label_51 = QLabel(self.gridLayoutWidget_2)
        self.label_51.setObjectName(u"label_51")

        self.gridLayout_2.addWidget(self.label_51, 8, 0, 1, 1)

        self.label_48 = QLabel(self.gridLayoutWidget_2)
        self.label_48.setObjectName(u"label_48")

        self.gridLayout_2.addWidget(self.label_48, 5, 0, 1, 1)

        self.label_35 = QLabel(self.gridLayoutWidget_2)
        self.label_35.setObjectName(u"label_35")

        self.gridLayout_2.addWidget(self.label_35, 2, 2, 1, 1)

        self.label_44 = QLabel(self.gridLayoutWidget_2)
        self.label_44.setObjectName(u"label_44")

        self.gridLayout_2.addWidget(self.label_44, 9, 2, 1, 1)

        self.lineEdit_joint4_ = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint4_.setObjectName(u"lineEdit_joint4_")

        self.gridLayout_2.addWidget(self.lineEdit_joint4_, 7, 1, 1, 1)

        self.label_32 = QLabel(self.gridLayoutWidget_2)
        self.label_32.setObjectName(u"label_32")

        self.gridLayout_2.addWidget(self.label_32, 1, 0, 1, 1)

        self.lineEdit_joint3 = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint3.setObjectName(u"lineEdit_joint3")

        self.gridLayout_2.addWidget(self.lineEdit_joint3, 4, 1, 1, 1)

        self.label_37 = QLabel(self.gridLayoutWidget_2)
        self.label_37.setObjectName(u"label_37")

        self.gridLayout_2.addWidget(self.label_37, 3, 2, 1, 1)

        self.lineEdit_joint1 = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint1.setObjectName(u"lineEdit_joint1")

        self.gridLayout_2.addWidget(self.lineEdit_joint1, 0, 1, 1, 1)

        self.lineEdit_joint1_ = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint1_.setObjectName(u"lineEdit_joint1_")

        self.gridLayout_2.addWidget(self.lineEdit_joint1_, 1, 1, 1, 1)

        self.label_54 = QLabel(self.gridLayoutWidget_2)
        self.label_54.setObjectName(u"label_54")

        self.gridLayout_2.addWidget(self.label_54, 11, 0, 1, 1)

        self.label_39 = QLabel(self.gridLayoutWidget_2)
        self.label_39.setObjectName(u"label_39")

        self.gridLayout_2.addWidget(self.label_39, 4, 2, 1, 1)

        self.label_43 = QLabel(self.gridLayoutWidget_2)
        self.label_43.setObjectName(u"label_43")

        self.gridLayout_2.addWidget(self.label_43, 8, 2, 1, 1)

        self.label_42 = QLabel(self.gridLayoutWidget_2)
        self.label_42.setObjectName(u"label_42")

        self.gridLayout_2.addWidget(self.label_42, 7, 2, 1, 1)

        self.lineEdit_joint2 = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint2.setObjectName(u"lineEdit_joint2")

        self.gridLayout_2.addWidget(self.lineEdit_joint2, 2, 1, 1, 1)

        self.label_45 = QLabel(self.gridLayoutWidget_2)
        self.label_45.setObjectName(u"label_45")

        self.gridLayout_2.addWidget(self.label_45, 10, 2, 1, 1)

        self.label_50 = QLabel(self.gridLayoutWidget_2)
        self.label_50.setObjectName(u"label_50")

        self.gridLayout_2.addWidget(self.label_50, 7, 0, 1, 1)

        self.lineEdit_joint4 = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint4.setObjectName(u"lineEdit_joint4")

        self.gridLayout_2.addWidget(self.lineEdit_joint4, 6, 1, 1, 1)

        self.label_53 = QLabel(self.gridLayoutWidget_2)
        self.label_53.setObjectName(u"label_53")

        self.gridLayout_2.addWidget(self.label_53, 10, 0, 1, 1)

        self.label_36 = QLabel(self.gridLayoutWidget_2)
        self.label_36.setObjectName(u"label_36")

        self.gridLayout_2.addWidget(self.label_36, 3, 0, 1, 1)

        self.label_49 = QLabel(self.gridLayoutWidget_2)
        self.label_49.setObjectName(u"label_49")

        self.gridLayout_2.addWidget(self.label_49, 6, 0, 1, 1)

        self.lineEdit_joint6 = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint6.setObjectName(u"lineEdit_joint6")

        self.gridLayout_2.addWidget(self.lineEdit_joint6, 10, 1, 1, 1)

        self.lineEdit_joint2_ = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint2_.setObjectName(u"lineEdit_joint2_")

        self.gridLayout_2.addWidget(self.lineEdit_joint2_, 3, 1, 1, 1)

        self.lineEdit_joint5 = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint5.setObjectName(u"lineEdit_joint5")

        self.gridLayout_2.addWidget(self.lineEdit_joint5, 8, 1, 1, 1)

        self.lineEdit_joint3_ = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint3_.setObjectName(u"lineEdit_joint3_")

        self.gridLayout_2.addWidget(self.lineEdit_joint3_, 5, 1, 1, 1)

        self.label_41 = QLabel(self.gridLayoutWidget_2)
        self.label_41.setObjectName(u"label_41")

        self.gridLayout_2.addWidget(self.label_41, 6, 2, 1, 1)

        self.label_38 = QLabel(self.gridLayoutWidget_2)
        self.label_38.setObjectName(u"label_38")

        self.gridLayout_2.addWidget(self.label_38, 1, 2, 1, 1)

        self.label_33 = QLabel(self.gridLayoutWidget_2)
        self.label_33.setObjectName(u"label_33")

        self.gridLayout_2.addWidget(self.label_33, 0, 2, 1, 1)

        self.label_40 = QLabel(self.gridLayoutWidget_2)
        self.label_40.setObjectName(u"label_40")

        self.gridLayout_2.addWidget(self.label_40, 5, 2, 1, 1)

        self.label_52 = QLabel(self.gridLayoutWidget_2)
        self.label_52.setObjectName(u"label_52")

        self.gridLayout_2.addWidget(self.label_52, 9, 0, 1, 1)

        self.label_34 = QLabel(self.gridLayoutWidget_2)
        self.label_34.setObjectName(u"label_34")

        self.gridLayout_2.addWidget(self.label_34, 2, 0, 1, 1)

        self.label_47 = QLabel(self.gridLayoutWidget_2)
        self.label_47.setObjectName(u"label_47")

        self.gridLayout_2.addWidget(self.label_47, 4, 0, 1, 1)

        self.lineEdit_joint6_ = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint6_.setObjectName(u"lineEdit_joint6_")

        self.gridLayout_2.addWidget(self.lineEdit_joint6_, 11, 1, 1, 1)

        self.label_55 = QLabel(self.gridLayoutWidget_2)
        self.label_55.setObjectName(u"label_55")

        self.gridLayout_2.addWidget(self.label_55, 12, 0, 1, 1)

        self.label_56 = QLabel(self.gridLayoutWidget_2)
        self.label_56.setObjectName(u"label_56")

        self.gridLayout_2.addWidget(self.label_56, 13, 0, 1, 1)

        self.lineEdit_joint7 = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint7.setObjectName(u"lineEdit_joint7")

        self.gridLayout_2.addWidget(self.lineEdit_joint7, 12, 1, 1, 1)

        self.lineEdit_joint7_ = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_joint7_.setObjectName(u"lineEdit_joint7_")

        self.gridLayout_2.addWidget(self.lineEdit_joint7_, 13, 1, 1, 1)

        self.label_57 = QLabel(self.gridLayoutWidget_2)
        self.label_57.setObjectName(u"label_57")

        self.gridLayout_2.addWidget(self.label_57, 12, 2, 1, 1)

        self.label_58 = QLabel(self.gridLayoutWidget_2)
        self.label_58.setObjectName(u"label_58")

        self.gridLayout_2.addWidget(self.label_58, 13, 2, 1, 1)

        self.comboBox_3_length = QComboBox(self.tab_arm)
        self.comboBox_3_length.setObjectName(u"comboBox_3_length")
        self.comboBox_3_length.setGeometry(QRect(80, 420, 93, 26))
        self.comboBox_2_length = QComboBox(self.tab_arm)
        self.comboBox_2_length.setObjectName(u"comboBox_2_length")
        self.comboBox_2_length.setGeometry(QRect(80, 390, 93, 26))
        self.tabWidget.addTab(self.tab_arm, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.btn_dynamics_real_torq = QPushButton(self.tab)
        self.btn_dynamics_real_torq.setObjectName(u"btn_dynamics_real_torq")
        self.btn_dynamics_real_torq.setGeometry(QRect(290, 110, 121, 33))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_dynamics_real_torq.setPalette(palette2)
        self.btn_dynamics_real_torq.setFont(font2)
        self.btn_dynamics_real_torq.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.label_20 = QLabel(self.tab)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(30, 110, 241, 17))
        self.btn_dynamics_para_ident = QPushButton(self.tab)
        self.btn_dynamics_para_ident.setObjectName(u"btn_dynamics_para_ident")
        self.btn_dynamics_para_ident.setGeometry(QRect(60, 200, 331, 33))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_dynamics_para_ident.setPalette(palette3)
        self.btn_dynamics_para_ident.setFont(font2)
        self.btn_dynamics_para_ident.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.btn_dynamics_save_para = QPushButton(self.tab)
        self.btn_dynamics_save_para.setObjectName(u"btn_dynamics_save_para")
        self.btn_dynamics_save_para.setGeometry(QRect(140, 280, 161, 33))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_dynamics_save_para.setPalette(palette4)
        self.btn_dynamics_save_para.setFont(font2)
        self.btn_dynamics_save_para.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.label_21 = QLabel(self.tab)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 40, 251, 17))
        self.btn_dynamics_new_traj = QPushButton(self.tab)
        self.btn_dynamics_new_traj.setObjectName(u"btn_dynamics_new_traj")
        self.btn_dynamics_new_traj.setGeometry(QRect(290, 40, 121, 33))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_dynamics_new_traj.setPalette(palette5)
        self.btn_dynamics_new_traj.setFont(font2)
        self.btn_dynamics_new_traj.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.btn_traj_torque_plot = QPushButton(self.tab)
        self.btn_traj_torque_plot.setObjectName(u"btn_traj_torque_plot")
        self.btn_traj_torque_plot.setGeometry(QRect(480, 40, 121, 33))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_traj_torque_plot.setPalette(palette6)
        self.btn_traj_torque_plot.setFont(font2)
        self.btn_traj_torque_plot.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.tabWidget.addTab(self.tab, "")
        self.tab_mission = QWidget()
        self.tab_mission.setObjectName(u"tab_mission")
        self.btn_dynamics = QPushButton(self.tab_mission)
        self.btn_dynamics.setObjectName(u"btn_dynamics")
        self.btn_dynamics.setGeometry(QRect(470, 420, 201, 33))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_dynamics.setPalette(palette7)
        self.btn_dynamics.setFont(font2)
        self.btn_dynamics.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.lineEdit_payload = QLineEdit(self.tab_mission)
        self.lineEdit_payload.setObjectName(u"lineEdit_payload")
        self.lineEdit_payload.setGeometry(QRect(20, 200, 71, 26))
        self.lineEdit_vel_0 = QLineEdit(self.tab_mission)
        self.lineEdit_vel_0.setObjectName(u"lineEdit_vel_0")
        self.lineEdit_vel_0.setGeometry(QRect(20, 280, 61, 26))
        self.label = QLabel(self.tab_mission)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 170, 67, 17))
        self.label_2 = QLabel(self.tab_mission)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 240, 221, 17))
        self.label_3 = QLabel(self.tab_mission)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 320, 281, 17))
        self.lineEdit_vel_1 = QLineEdit(self.tab_mission)
        self.lineEdit_vel_1.setObjectName(u"lineEdit_vel_1")
        self.lineEdit_vel_1.setGeometry(QRect(90, 280, 61, 26))
        self.lineEdit_vel_2 = QLineEdit(self.tab_mission)
        self.lineEdit_vel_2.setObjectName(u"lineEdit_vel_2")
        self.lineEdit_vel_2.setGeometry(QRect(160, 280, 61, 26))
        self.lineEdit_vel_3 = QLineEdit(self.tab_mission)
        self.lineEdit_vel_3.setObjectName(u"lineEdit_vel_3")
        self.lineEdit_vel_3.setGeometry(QRect(230, 280, 61, 26))
        self.lineEdit_vel_4 = QLineEdit(self.tab_mission)
        self.lineEdit_vel_4.setObjectName(u"lineEdit_vel_4")
        self.lineEdit_vel_4.setGeometry(QRect(300, 280, 61, 26))
        self.lineEdit_vel_5 = QLineEdit(self.tab_mission)
        self.lineEdit_vel_5.setObjectName(u"lineEdit_vel_5")
        self.lineEdit_vel_5.setGeometry(QRect(370, 280, 61, 26))
        self.lineEdit_acc_2 = QLineEdit(self.tab_mission)
        self.lineEdit_acc_2.setObjectName(u"lineEdit_acc_2")
        self.lineEdit_acc_2.setGeometry(QRect(160, 350, 61, 26))
        self.lineEdit_acc_5 = QLineEdit(self.tab_mission)
        self.lineEdit_acc_5.setObjectName(u"lineEdit_acc_5")
        self.lineEdit_acc_5.setGeometry(QRect(370, 350, 61, 26))
        self.lineEdit_acc_4 = QLineEdit(self.tab_mission)
        self.lineEdit_acc_4.setObjectName(u"lineEdit_acc_4")
        self.lineEdit_acc_4.setGeometry(QRect(300, 350, 61, 26))
        self.lineEdit_acc_1 = QLineEdit(self.tab_mission)
        self.lineEdit_acc_1.setObjectName(u"lineEdit_acc_1")
        self.lineEdit_acc_1.setGeometry(QRect(90, 350, 61, 26))
        self.lineEdit_acc_3 = QLineEdit(self.tab_mission)
        self.lineEdit_acc_3.setObjectName(u"lineEdit_acc_3")
        self.lineEdit_acc_3.setGeometry(QRect(230, 350, 61, 26))
        self.lineEdit_acc_0 = QLineEdit(self.tab_mission)
        self.lineEdit_acc_0.setObjectName(u"lineEdit_acc_0")
        self.lineEdit_acc_0.setGeometry(QRect(20, 350, 61, 26))
        self.label_4 = QLabel(self.tab_mission)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(100, 200, 31, 17))
        self.lineEdit_payload_x = QLineEdit(self.tab_mission)
        self.lineEdit_payload_x.setObjectName(u"lineEdit_payload_x")
        self.lineEdit_payload_x.setGeometry(QRect(160, 200, 71, 26))
        self.lineEdit_payload_y = QLineEdit(self.tab_mission)
        self.lineEdit_payload_y.setObjectName(u"lineEdit_payload_y")
        self.lineEdit_payload_y.setGeometry(QRect(240, 200, 71, 26))
        self.lineEdit_payload_z = QLineEdit(self.tab_mission)
        self.lineEdit_payload_z.setObjectName(u"lineEdit_payload_z")
        self.lineEdit_payload_z.setGeometry(QRect(320, 200, 71, 26))
        self.label_5 = QLabel(self.tab_mission)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(160, 170, 161, 17))
        self.btn_dyn_set = QPushButton(self.tab_mission)
        self.btn_dyn_set.setObjectName(u"btn_dyn_set")
        self.btn_dyn_set.setGeometry(QRect(340, 400, 91, 33))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush3 = QBrush(QColor(0, 210, 26, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.btn_dyn_set.setPalette(palette8)
        self.btn_dyn_set.setFont(font2)
        self.btn_dyn_set.setStyleSheet(u"background-color:#00d21a;color:white;border-color: black;")
        self.lineEdit_jog_3 = QLineEdit(self.tab_mission)
        self.lineEdit_jog_3.setObjectName(u"lineEdit_jog_3")
        self.lineEdit_jog_3.setGeometry(QRect(230, 70, 61, 26))
        self.lineEdit_jog_1 = QLineEdit(self.tab_mission)
        self.lineEdit_jog_1.setObjectName(u"lineEdit_jog_1")
        self.lineEdit_jog_1.setGeometry(QRect(90, 70, 61, 26))
        self.lineEdit_jog_5 = QLineEdit(self.tab_mission)
        self.lineEdit_jog_5.setObjectName(u"lineEdit_jog_5")
        self.lineEdit_jog_5.setGeometry(QRect(370, 70, 61, 26))
        self.lineEdit_jog_4 = QLineEdit(self.tab_mission)
        self.lineEdit_jog_4.setObjectName(u"lineEdit_jog_4")
        self.lineEdit_jog_4.setGeometry(QRect(300, 70, 61, 26))
        self.lineEdit_jog_2 = QLineEdit(self.tab_mission)
        self.lineEdit_jog_2.setObjectName(u"lineEdit_jog_2")
        self.lineEdit_jog_2.setGeometry(QRect(160, 70, 61, 26))
        self.label_6 = QLabel(self.tab_mission)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 30, 191, 17))
        self.lineEdit_jog_0 = QLineEdit(self.tab_mission)
        self.lineEdit_jog_0.setObjectName(u"lineEdit_jog_0")
        self.lineEdit_jog_0.setGeometry(QRect(20, 70, 61, 26))
        self.btn_arm_plot = QPushButton(self.tab_mission)
        self.btn_arm_plot.setObjectName(u"btn_arm_plot")
        self.btn_arm_plot.setGeometry(QRect(230, 120, 91, 33))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.btn_arm_plot.setPalette(palette9)
        self.btn_arm_plot.setFont(font2)
        self.btn_arm_plot.setStyleSheet(u"background-color:#00d21a;color:white;border-color: black;")
        self.btn_arm_plot_close = QPushButton(self.tab_mission)
        self.btn_arm_plot_close.setObjectName(u"btn_arm_plot_close")
        self.btn_arm_plot_close.setGeometry(QRect(340, 120, 91, 33))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.btn_arm_plot_close.setPalette(palette10)
        self.btn_arm_plot_close.setFont(font2)
        self.btn_arm_plot_close.setStyleSheet(u"background-color:#00d21a;color:white;border-color: black;")
        self.btn_dyn_torque_limit = QPushButton(self.tab_mission)
        self.btn_dyn_torque_limit.setObjectName(u"btn_dyn_torque_limit")
        self.btn_dyn_torque_limit.setGeometry(QRect(540, 370, 131, 33))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette11.setBrush(QPalette.Active, QPalette.Text, brush)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette11.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.btn_dyn_torque_limit.setPalette(palette11)
        self.btn_dyn_torque_limit.setFont(font2)
        self.btn_dyn_torque_limit.setStyleSheet(u"background-color:#00d21a;color:white;border-color: black;")
        self.lineEdit_jog_6 = QLineEdit(self.tab_mission)
        self.lineEdit_jog_6.setObjectName(u"lineEdit_jog_6")
        self.lineEdit_jog_6.setGeometry(QRect(440, 70, 61, 26))
        self.lineEdit_vel_6 = QLineEdit(self.tab_mission)
        self.lineEdit_vel_6.setObjectName(u"lineEdit_vel_6")
        self.lineEdit_vel_6.setGeometry(QRect(440, 280, 61, 26))
        self.lineEdit_acc_6 = QLineEdit(self.tab_mission)
        self.lineEdit_acc_6.setObjectName(u"lineEdit_acc_6")
        self.lineEdit_acc_6.setGeometry(QRect(440, 350, 61, 26))
        self.tabWidget.addTab(self.tab_mission, "")
        self.tab_state = QWidget()
        self.tab_state.setObjectName(u"tab_state")
        self.btn_dyn_space = QPushButton(self.tab_state)
        self.btn_dyn_space.setObjectName(u"btn_dyn_space")
        self.btn_dyn_space.setGeometry(QRect(430, 340, 201, 33))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette12.setBrush(QPalette.Active, QPalette.Text, brush)
        palette12.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette12.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette12.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette12.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.btn_dyn_space.setPalette(palette12)
        self.btn_dyn_space.setFont(font2)
        self.btn_dyn_space.setStyleSheet(u"background-color:#00d21a;color:white;border-color: black;")
        self.btn_dyn_axis_set = QPushButton(self.tab_state)
        self.btn_dyn_axis_set.setObjectName(u"btn_dyn_axis_set")
        self.btn_dyn_axis_set.setGeometry(QRect(140, 240, 91, 33))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette13.setBrush(QPalette.Active, QPalette.Text, brush)
        palette13.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette13.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette13.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette13.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.btn_dyn_axis_set.setPalette(palette13)
        self.btn_dyn_axis_set.setFont(font2)
        self.btn_dyn_axis_set.setStyleSheet(u"background-color:#00d21a;color:white;border-color: black;")
        self.lineEdit_axis_set = QLineEdit(self.tab_state)
        self.lineEdit_axis_set.setObjectName(u"lineEdit_axis_set")
        self.lineEdit_axis_set.setGeometry(QRect(40, 240, 61, 26))
        self.label_7 = QLabel(self.tab_state)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 200, 151, 17))
        self.lineEdit_payload_space = QLineEdit(self.tab_state)
        self.lineEdit_payload_space.setObjectName(u"lineEdit_payload_space")
        self.lineEdit_payload_space.setGeometry(QRect(30, 70, 71, 26))
        self.label_15 = QLabel(self.tab_state)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 40, 67, 17))
        self.label_16 = QLabel(self.tab_state)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(110, 70, 31, 17))
        self.label_17 = QLabel(self.tab_state)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(170, 40, 161, 17))
        self.lineEdit_payload_y_space = QLineEdit(self.tab_state)
        self.lineEdit_payload_y_space.setObjectName(u"lineEdit_payload_y_space")
        self.lineEdit_payload_y_space.setGeometry(QRect(250, 70, 71, 26))
        self.lineEdit_payload_x_space = QLineEdit(self.tab_state)
        self.lineEdit_payload_x_space.setObjectName(u"lineEdit_payload_x_space")
        self.lineEdit_payload_x_space.setGeometry(QRect(170, 70, 71, 26))
        self.lineEdit_payload_z_space = QLineEdit(self.tab_state)
        self.lineEdit_payload_z_space.setObjectName(u"lineEdit_payload_z_space")
        self.lineEdit_payload_z_space.setGeometry(QRect(330, 70, 71, 26))
        self.btn_dyn_space_set = QPushButton(self.tab_state)
        self.btn_dyn_space_set.setObjectName(u"btn_dyn_space_set")
        self.btn_dyn_space_set.setGeometry(QRect(300, 120, 91, 33))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette14.setBrush(QPalette.Active, QPalette.Text, brush)
        palette14.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette14.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette14.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.btn_dyn_space_set.setPalette(palette14)
        self.btn_dyn_space_set.setFont(font2)
        self.btn_dyn_space_set.setStyleSheet(u"background-color:#00d21a;color:white;border-color: black;")
        self.widget = roundProgressBar(self.tab_state)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(480, 200, 120, 80))
        self.tabWidget.addTab(self.tab_state, "")
        self.tab_other = QWidget()
        self.tab_other.setObjectName(u"tab_other")
        self.btn_random_robot_structure = QPushButton(self.tab_other)
        self.btn_random_robot_structure.setObjectName(u"btn_random_robot_structure")
        self.btn_random_robot_structure.setGeometry(QRect(20, 10, 261, 33))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Text, brush)
        palette15.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_random_robot_structure.setPalette(palette15)
        self.btn_random_robot_structure.setFont(font2)
        self.btn_random_robot_structure.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.btn_random_robot_motor = QPushButton(self.tab_other)
        self.btn_random_robot_motor.setObjectName(u"btn_random_robot_motor")
        self.btn_random_robot_motor.setGeometry(QRect(20, 50, 261, 33))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette16.setBrush(QPalette.Active, QPalette.Text, brush)
        palette16.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette16.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette16.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_random_robot_motor.setPalette(palette16)
        self.btn_random_robot_motor.setFont(font2)
        self.btn_random_robot_motor.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.btn_optimization_set = QPushButton(self.tab_other)
        self.btn_optimization_set.setObjectName(u"btn_optimization_set")
        self.btn_optimization_set.setGeometry(QRect(380, 90, 261, 33))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette17.setBrush(QPalette.Active, QPalette.Text, brush)
        palette17.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette17.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_optimization_set.setPalette(palette17)
        self.btn_optimization_set.setFont(font2)
        self.btn_optimization_set.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.lineEdit_op_acc_4 = QLineEdit(self.tab_other)
        self.lineEdit_op_acc_4.setObjectName(u"lineEdit_op_acc_4")
        self.lineEdit_op_acc_4.setGeometry(QRect(220, 320, 61, 26))
        self.lineEdit_op_acc_1 = QLineEdit(self.tab_other)
        self.lineEdit_op_acc_1.setObjectName(u"lineEdit_op_acc_1")
        self.lineEdit_op_acc_1.setGeometry(QRect(10, 320, 61, 26))
        self.lineEdit_op_vel_5 = QLineEdit(self.tab_other)
        self.lineEdit_op_vel_5.setObjectName(u"lineEdit_op_vel_5")
        self.lineEdit_op_vel_5.setGeometry(QRect(290, 250, 61, 26))
        self.lineEdit_op_acc_5 = QLineEdit(self.tab_other)
        self.lineEdit_op_acc_5.setObjectName(u"lineEdit_op_acc_5")
        self.lineEdit_op_acc_5.setGeometry(QRect(290, 320, 61, 26))
        self.lineEdit_op_payload_y = QLineEdit(self.tab_other)
        self.lineEdit_op_payload_y.setObjectName(u"lineEdit_op_payload_y")
        self.lineEdit_op_payload_y.setGeometry(QRect(230, 170, 71, 26))
        self.label_25 = QLabel(self.tab_other)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(150, 140, 161, 17))
        self.label_24 = QLabel(self.tab_other)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 290, 261, 17))
        self.lineEdit_op_vel_2 = QLineEdit(self.tab_other)
        self.lineEdit_op_vel_2.setObjectName(u"lineEdit_op_vel_2")
        self.lineEdit_op_vel_2.setGeometry(QRect(80, 250, 61, 26))
        self.label_27 = QLabel(self.tab_other)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 140, 67, 17))
        self.lineEdit_op_payload = QLineEdit(self.tab_other)
        self.lineEdit_op_payload.setObjectName(u"lineEdit_op_payload")
        self.lineEdit_op_payload.setGeometry(QRect(10, 170, 71, 26))
        self.label_26 = QLabel(self.tab_other)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(90, 170, 31, 17))
        self.lineEdit_op_payload_x = QLineEdit(self.tab_other)
        self.lineEdit_op_payload_x.setObjectName(u"lineEdit_op_payload_x")
        self.lineEdit_op_payload_x.setGeometry(QRect(150, 170, 71, 26))
        self.lineEdit_op_vel_1 = QLineEdit(self.tab_other)
        self.lineEdit_op_vel_1.setObjectName(u"lineEdit_op_vel_1")
        self.lineEdit_op_vel_1.setGeometry(QRect(10, 250, 61, 26))
        self.lineEdit_op_payload_z = QLineEdit(self.tab_other)
        self.lineEdit_op_payload_z.setObjectName(u"lineEdit_op_payload_z")
        self.lineEdit_op_payload_z.setGeometry(QRect(310, 170, 71, 26))
        self.lineEdit_op_vel_6 = QLineEdit(self.tab_other)
        self.lineEdit_op_vel_6.setObjectName(u"lineEdit_op_vel_6")
        self.lineEdit_op_vel_6.setGeometry(QRect(360, 250, 61, 26))
        self.btn_structure_select = QPushButton(self.tab_other)
        self.btn_structure_select.setObjectName(u"btn_structure_select")
        self.btn_structure_select.setGeometry(QRect(550, 40, 91, 33))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette18.setBrush(QPalette.Active, QPalette.Text, brush)
        palette18.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette18.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette18.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette18.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette18.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette18.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.btn_structure_select.setPalette(palette18)
        self.btn_structure_select.setFont(font2)
        self.btn_structure_select.setStyleSheet(u"background-color:#00d21a;color:white;border-color: black;")
        self.lineEdit_op_vel_3 = QLineEdit(self.tab_other)
        self.lineEdit_op_vel_3.setObjectName(u"lineEdit_op_vel_3")
        self.lineEdit_op_vel_3.setGeometry(QRect(150, 250, 61, 26))
        self.label_10 = QLabel(self.tab_other)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 210, 211, 17))
        self.lineEdit_op_vel_4 = QLineEdit(self.tab_other)
        self.lineEdit_op_vel_4.setObjectName(u"lineEdit_op_vel_4")
        self.lineEdit_op_vel_4.setGeometry(QRect(220, 250, 61, 26))
        self.lineEdit_op_acc_3 = QLineEdit(self.tab_other)
        self.lineEdit_op_acc_3.setObjectName(u"lineEdit_op_acc_3")
        self.lineEdit_op_acc_3.setGeometry(QRect(150, 320, 61, 26))
        self.lineEdit_op_acc_2 = QLineEdit(self.tab_other)
        self.lineEdit_op_acc_2.setObjectName(u"lineEdit_op_acc_2")
        self.lineEdit_op_acc_2.setGeometry(QRect(80, 320, 61, 26))
        self.lineEdit_op_acc_6 = QLineEdit(self.tab_other)
        self.lineEdit_op_acc_6.setObjectName(u"lineEdit_op_acc_6")
        self.lineEdit_op_acc_6.setGeometry(QRect(360, 320, 61, 26))
        self.label_29 = QLabel(self.tab_other)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 370, 145, 26))
        self.lineEdit_op_reachable_radius = QLineEdit(self.tab_other)
        self.lineEdit_op_reachable_radius.setObjectName(u"lineEdit_op_reachable_radius")
        self.lineEdit_op_reachable_radius.setGeometry(QRect(160, 370, 174, 26))
        self.label_30 = QLabel(self.tab_other)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(340, 350, 20, 71))
        self.lineEdit_op_acc_7 = QLineEdit(self.tab_other)
        self.lineEdit_op_acc_7.setObjectName(u"lineEdit_op_acc_7")
        self.lineEdit_op_acc_7.setGeometry(QRect(430, 320, 61, 26))
        self.lineEdit_op_vel_7 = QLineEdit(self.tab_other)
        self.lineEdit_op_vel_7.setObjectName(u"lineEdit_op_vel_7")
        self.lineEdit_op_vel_7.setGeometry(QRect(430, 250, 61, 26))
        self.comboBox_dof_select = QComboBox(self.tab_other)
        self.comboBox_dof_select.setObjectName(u"comboBox_dof_select")
        self.comboBox_dof_select.setGeometry(QRect(440, 10, 93, 26))
        self.label_dof = QLabel(self.tab_other)
        self.label_dof.setObjectName(u"label_dof")
        self.label_dof.setGeometry(QRect(380, 10, 31, 26))
        self.comboBox_structure_select = QComboBox(self.tab_other)
        self.comboBox_structure_select.setObjectName(u"comboBox_structure_select")
        self.comboBox_structure_select.setGeometry(QRect(440, 50, 93, 26))
        self.label_dof_2 = QLabel(self.tab_other)
        self.label_dof_2.setObjectName(u"label_dof_2")
        self.label_dof_2.setGeometry(QRect(320, 50, 91, 26))
        self.btn_optimization_analysis = QPushButton(self.tab_other)
        self.btn_optimization_analysis.setObjectName(u"btn_optimization_analysis")
        self.btn_optimization_analysis.setGeometry(QRect(390, 370, 261, 33))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette19.setBrush(QPalette.Active, QPalette.Text, brush)
        palette19.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette19.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette19.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette19.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette19.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette19.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette19.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_optimization_analysis.setPalette(palette19)
        self.btn_optimization_analysis.setFont(font2)
        self.btn_optimization_analysis.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.label_59 = QLabel(self.tab_other)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(400, 150, 61, 26))
        self.label_60 = QLabel(self.tab_other)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(570, 130, 20, 71))
        self.lineEdit_op_weight = QLineEdit(self.tab_other)
        self.lineEdit_op_weight.setObjectName(u"lineEdit_op_weight")
        self.lineEdit_op_weight.setGeometry(QRect(470, 150, 91, 26))
        self.lineEdit_op_cost = QLineEdit(self.tab_other)
        self.lineEdit_op_cost.setObjectName(u"lineEdit_op_cost")
        self.lineEdit_op_cost.setGeometry(QRect(470, 200, 91, 26))
        self.label_62 = QLabel(self.tab_other)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(400, 200, 61, 26))
        self.btn_optimization_test = QPushButton(self.tab_other)
        self.btn_optimization_test.setObjectName(u"btn_optimization_test")
        self.btn_optimization_test.setGeometry(QRect(390, 420, 261, 33))
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette20.setBrush(QPalette.Active, QPalette.Text, brush)
        palette20.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette20.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette20.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette20.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette20.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette20.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette20.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette20.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette20.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_optimization_test.setPalette(palette20)
        self.btn_optimization_test.setFont(font2)
        self.btn_optimization_test.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.lineEdit_op_test_model_name = QLineEdit(self.tab_other)
        self.lineEdit_op_test_model_name.setObjectName(u"lineEdit_op_test_model_name")
        self.lineEdit_op_test_model_name.setGeometry(QRect(210, 430, 174, 26))
        self.label_61 = QLabel(self.tab_other)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(100, 430, 101, 26))
        self.tabWidget.addTab(self.tab_other, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.btn_cjm_select = QPushButton(self.tab_2)
        self.btn_cjm_select.setObjectName(u"btn_cjm_select")
        self.btn_cjm_select.setGeometry(QRect(30, 40, 261, 33))
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette21.setBrush(QPalette.Active, QPalette.Text, brush)
        palette21.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette21.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette21.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette21.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette21.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette21.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette21.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette21.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette21.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette21.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette21.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette21.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_cjm_select.setPalette(palette21)
        self.btn_cjm_select.setFont(font2)
        self.btn_cjm_select.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 687, 23))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Control Window", None))
#if QT_CONFIG(whatsthis)
        self.tabWidget.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>dd</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.lineEdit_payload_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Axis 3 length", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Payload", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Axis 2 length", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"DoF", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"kg", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Reachable radius", None))
        self.lineEdit_reachable_radius.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"mm", None))
        self.lineEdit_3_length.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lineEdit_2_length.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.btn_dynamics_design.setText(QCoreApplication.translate("MainWindow", u"Design", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Joint 1+", None))
        self.lineEdit_joint5_.setText(QCoreApplication.translate("MainWindow", u"-176", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Joint 5+", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Joint 3-", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.lineEdit_joint4_.setText(QCoreApplication.translate("MainWindow", u"-176", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Joint 1-", None))
        self.lineEdit_joint3.setText(QCoreApplication.translate("MainWindow", u"176", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.lineEdit_joint1.setText(QCoreApplication.translate("MainWindow", u"176", None))
        self.lineEdit_joint1_.setText(QCoreApplication.translate("MainWindow", u"-176", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"Joint 6-", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.lineEdit_joint2.setText(QCoreApplication.translate("MainWindow", u"176", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Joint 4-", None))
        self.lineEdit_joint4.setText(QCoreApplication.translate("MainWindow", u"176", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"Joint 6+", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Joint 2-", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Joint 4+", None))
        self.lineEdit_joint6.setText(QCoreApplication.translate("MainWindow", u"176", None))
        self.lineEdit_joint2_.setText(QCoreApplication.translate("MainWindow", u"-176", None))
        self.lineEdit_joint5.setText(QCoreApplication.translate("MainWindow", u"176", None))
        self.lineEdit_joint3_.setText(QCoreApplication.translate("MainWindow", u"-176", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"Joint 5-", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Joint 2+", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Joint 3+", None))
        self.lineEdit_joint6_.setText(QCoreApplication.translate("MainWindow", u"-176", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"Joint 7+", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"Joint 7-", None))
        self.lineEdit_joint7.setText(QCoreApplication.translate("MainWindow", u"176", None))
        self.lineEdit_joint7_.setText(QCoreApplication.translate("MainWindow", u"-176", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_arm), QCoreApplication.translate("MainWindow", u"Arm Design", None))
        self.btn_dynamics_real_torq.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Read Real Arm Torque", None))
        self.btn_dynamics_para_ident.setText(QCoreApplication.translate("MainWindow", u"Dynamic Parameter Identification", None))
        self.btn_dynamics_save_para.setText(QCoreApplication.translate("MainWindow", u"Save Parameter", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"New Excitation Trajectories", None))
        self.btn_dynamics_new_traj.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.btn_traj_torque_plot.setText(QCoreApplication.translate("MainWindow", u"Plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Parameter Identification", None))
        self.btn_dynamics.setText(QCoreApplication.translate("MainWindow", u"Dynamics  Calculation", None))
        self.lineEdit_payload.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_vel_0.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Payload", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Angular velocity(rad/s)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Angular acceleration(rad/s^2)", None))
        self.lineEdit_vel_1.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_vel_2.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_vel_3.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_vel_4.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_vel_5.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_acc_2.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_acc_5.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_acc_4.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_acc_1.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_acc_3.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_acc_0.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Kg", None))
        self.lineEdit_payload_x.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_payload_y.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_payload_z.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Payload Position", None))
        self.btn_dyn_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.lineEdit_jog_3.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_jog_1.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_jog_5.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_jog_4.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_jog_2.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Joint Angle (degree)", None))
        self.lineEdit_jog_0.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.btn_arm_plot.setText(QCoreApplication.translate("MainWindow", u"Plot", None))
        self.btn_arm_plot_close.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.btn_dyn_torque_limit.setText(QCoreApplication.translate("MainWindow", u"Torque Limit", None))
        self.lineEdit_jog_6.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_vel_6.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_acc_6.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mission), QCoreApplication.translate("MainWindow", u"Dynamics", None))
        self.btn_dyn_space.setText(QCoreApplication.translate("MainWindow", u"Dynamics Space", None))
        self.btn_dyn_axis_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.lineEdit_axis_set.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"select axis", None))
        self.lineEdit_payload_space.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Payload", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Kg", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Payload Position", None))
        self.lineEdit_payload_y_space.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_payload_x_space.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_payload_z_space.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.btn_dyn_space_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_state), QCoreApplication.translate("MainWindow", u"Dynamics Space", None))
        self.btn_random_robot_structure.setText(QCoreApplication.translate("MainWindow", u"random robot structure", None))
        self.btn_random_robot_motor.setText(QCoreApplication.translate("MainWindow", u"random robot & motor", None))
        self.btn_optimization_set.setText(QCoreApplication.translate("MainWindow", u"optimization set", None))
        self.lineEdit_op_acc_4.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.lineEdit_op_acc_1.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.lineEdit_op_vel_5.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.lineEdit_op_acc_5.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.lineEdit_op_payload_y.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Payload Position", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Angular acceleration(rad/s^2)", None))
        self.lineEdit_op_vel_2.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Payload", None))
        self.lineEdit_op_payload.setText(QCoreApplication.translate("MainWindow", u"3.0", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Kg", None))
        self.lineEdit_op_payload_x.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_op_vel_1.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.lineEdit_op_payload_z.setText(QCoreApplication.translate("MainWindow", u"0.04", None))
        self.lineEdit_op_vel_6.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.btn_structure_select.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.lineEdit_op_vel_3.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Angular velocity(rad/s)", None))
        self.lineEdit_op_vel_4.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.lineEdit_op_acc_3.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.lineEdit_op_acc_2.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.lineEdit_op_acc_6.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Reachable radius", None))
        self.lineEdit_op_reachable_radius.setText(QCoreApplication.translate("MainWindow", u"0.8", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.lineEdit_op_acc_7.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.lineEdit_op_vel_7.setText(QCoreApplication.translate("MainWindow", u"1.57", None))
        self.label_dof.setText(QCoreApplication.translate("MainWindow", u"DoF", None))
        self.label_dof_2.setText(QCoreApplication.translate("MainWindow", u"Structure", None))
        self.btn_optimization_analysis.setText(QCoreApplication.translate("MainWindow", u"optimization analysis", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"weight", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"kg", None))
        self.lineEdit_op_weight.setText(QCoreApplication.translate("MainWindow", u"1.6", None))
        self.lineEdit_op_cost.setText(QCoreApplication.translate("MainWindow", u"750", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"cost", None))
        self.btn_optimization_test.setText(QCoreApplication.translate("MainWindow", u"optimization test", None))
        self.lineEdit_op_test_model_name.setText("")
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"model name:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_other), QCoreApplication.translate("MainWindow", u"Other", None))
        self.btn_cjm_select.setText(QCoreApplication.translate("MainWindow", u"CJM Select ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"CJM", None))
    # retranslateUi

